services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-panaderia_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-panaderia_duran}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      API_URL: https://duran.nandev.online
    depends_on:
      - db
    networks:
      - default


  frontend:
    build:
      context: .
      dockerfile: web.Dockerfile
      args:
        API_URL: https://duran.nandev.online
    restart: always
    ports:
      - "3004:3000"
    depends_on:
      - backend
    networks:
      - default          # para hablar con backend internamente
      - dokploy-network  # para que Traefik lo descubra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tfg-panaderia.rule=Host(`duran.nandev.online`)"
      - "traefik.http.routers.tfg-panaderia.entrypoints=websecure"
      - "traefik.http.routers.tfg-panaderia.tls.certresolver=letsencrypt"
      - "traefik.http.services.tfg-panaderia.loadbalancer.server.port=3000"
      - "traefik.docker.network=dokploy-network"

networks:
  default:
    driver: bridge
  dokploy-network:
    external: true  # ← usa la red existente, no crea una nueva

volumes:
  pgdata:
