server {
    listen 3000;

    # Archivos estáticos del frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri.html $uri/index.html /__spa-fallback.html;
    }

    # Proxy al backend (websockets + API)
    location /_event {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /ping {
        proxy_pass http://backend:8000;
    }
}