services:
  app:
    image: local/reflex-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: ${NEON_DB}
      REFLEX_DB_URL: ${NEON_DB}
      REFLEX_REDIS_URL: redis://redis:6379
    volumes:
      - db-data:/app/data
      - upload-data:/app/uploaded_files
    restart: always
    depends_on:
      - redis

  webserver:
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - "8080:80"
    volumes:
      - caddy-data:/root/.caddy
    restart: always
    depends_on:
      - app

  redis:
    image: redis:7
    restart: always

volumes:
  db-data:
  upload-data:
  caddy-data:
